# Generated by Django 5.0.6 on 2024-06-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintModel',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('empleado', models.IntegerField(db_column='empleado', unique=True)),
                ('template', models.TextField()),
            ],
            options={
                'db_table': 'huellas',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario_id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('usuario_nombre', models.CharField(db_column='nombre', max_length=50)),
                ('usuario_correo', models.EmailField(db_column='correo', max_length=254, unique=True, verbose_name='Correo')),
                ('usuario_tipo', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'CLIENTE'), (3, 'EMPLEADO')], db_column='tipo', default=2)),
                ('password', models.TextField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
