# Generated by Django 5.0.6 on 2024-06-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintmodel',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fingerprintmodel',
            unique_together={('id', 'empleado')},
        ),
    ]
